---
name: Test Director
port: 8081

director:
  max_threads: 1

logging:
  level: ERROR

dir: /tmp/boshdir
db:
  adapter: sqlite
  database: '/:memory:'
  connection_options:
    max_connections: 32
    pool_timeout: 10
blobstore:
  provider: simple
  options:
    endpoint: http://127.0.0.1
    user: admin
    password:
snapshots:
  enabled: false
scan_and_fix:
  auto_fix_stateful_nodes: false
cloud:
  plugin: dummy
  properties:
    dir: ...
     # to be added
backup_destination:
  provider: s3
  options:
    bucket_name: foo
    access_key_id: asdf
    secret_access_key: zxcv
user_management:
  provider: local
  local:
    users:
    - {name: admin, password: admin}
config_server:
  enabled: false
record_events: true
