---
platform: linux

image_resource:
  type: docker-image
  source:
    # TODO: Change back to bosh/main when merging with master
    repository: jamlo/bosh-complete-ci

inputs:
- name: bosh-src
- name: bosh-cli
- name: bosh-agent

run:
  path: bosh-src/ci/tasks/test-upgrade.sh

params:
  RUBY_VERSION:      replace-me
  DB:                replace-me
  LOG_LEVEL:         ERROR
